import Head from "next/head";
export function Layout({ children }) {
  return (
    <main className="layout">
      <Head>
        <title>Find the best job for you</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </main>
  );
}
